using System.Collections.Generic;

namespace TestFramework.Data.Lists
{
    public class AddressDataList : IDataList<string>
    {
        public virtual List<string> List => new List<string>
        {
            "10th",
            "11th",
            "12th",
            "13th",
            "14th",
            "15th",
            "Acclaim",
            "Alborough",
            "Alcamo",
            "Alcott",
            "Alcoy",
            "Alder Creek",
            "Aldersgate",
            "Aldershot",
            "Alderson",
            "Alderwood",
            "Aldrich",
            "Alessandro",
            "Alex",
            "Alexander",
            "Alexandria",
            "Alexia",
            "Alexis",
            "Alfalfa",
            "Alfreda",
            "Algen",
            "Alice",
            "Alisa",
            "Allacante",
            "Allan Adale",
            "Allegheny",
            "Allegiance",
            "Allen",
            "Allende",
            "Alley",
            "Alley/Easement",
            "Allison",
            "Alma",
            "Almaden",
            "Almendro",
            "Almeria",
            "Almond",
            "Almond Blossom",
            "Almond Grove",
            "Almond Tree",
            "Almond Valley",
            "Almond Wood",
            "Almondcrest",
            "Almsbury",
            "Aloha",
            "Alondra",
            "Alonzo",
            "Alpha",
            "Alphonse",
            "Alpine",
            "Alpine Creek",
            "Amy",
            "Apple",
            "Apple Blossom",
            "Arroyo",
            "Arroyo Hondo",
            "Aulston",
            "Aura",
            "Aurora",
            "Aurthur Mace",
            "Austin",
            "Austin David",
            "Auto Center",
            "Auto Mall",
            "Autumn",
            "Autumn Ash",
            "Autumn Grove",
            "Beyerwood",
            "Bianco",
            "Big Ben",
            "Big Creek",
            "Big Oak",
            "Big Sky",
            "Big Sur",
            "Big Tree",
            "Bigaroon",
            "Bigben",
            "Bigelow",
            "Billy",
            "Cape Cod",
            "Capewood",
            "Capistrano",
            "Capital",
            "Capitol",
            "Capp",
            "Caprice",
            "Capricorn",
            "Capurso",
            "Caraway",
            "Cardiff",
            "Cardigan",
            "Cardinal",
            "Cardinal Flower",
            "Caribbean",
            "Carl",
            "Carla",
            "Carleen",
            "Carleton",
            "Carlisle",
            "Carlita",
            "Carlos",
            "Carlsbad Caverns",
            "Carlson",
            "Carlton",
            "Carly Creek",
            "Carma",
            "Carmel",
            "Carmella",
            "Carmen",
            "Carmichael",
            "Carmillita",
            "Carnation",
            "Carnegie",
            "Carnival",
            "Carnwood",
            "Carol",
            "Caroldeen",
            "Carolina",
            "Carolyn",
            "Carousel",
            "Carpathian",
            "Carpenter",
            "Carpintaro",
            "Carrboro",
            "Carriage",
            "Carrie",
            "Carrigan",
            "Carrousel",
            "Carsean",
            "Charbray",
            "Chardonnay",
            "Charity",
            "Charlemagne",
            "Charles",
            "Charleston",
            "Charline",
            "Charlotte",
            "Charlottesville",
            "Charter",
            "Chartwell",
            "Chase",
            "Chastanet",
            "Chateau",
            "Chateaugay",
            "Chatsworth",
            "Chaulet",
            "Chauncy",
            "Cheatham",
            "Chedworth",
            "Chehalem",
            "Chelmsford",
            "Chelsea",
            "Chelwood",
            "Chenault",
            "Chenin",
            "Cherise",
            "Cherish",
            "Cherokee",
            "Cherry",
            "Cherry Blossom",
            "Cherry Creek",
            "Cherry Hill",
            "Cherry Oak",
            "Cherry Tree",
            "Cherryglen",
            "Cherrywood",
            "Cheryl",
            "Chesapeake",
            "Cheshire",
            "Chesswell",
            "Chester",
            "Chesterfield",
            "Chestnut",
            "Chetwood",
            "Cheyenne",
            "Chianti",
            "Chiburis",
            "Chicago",
            "Chickaree",
            "Chief Tucker",
            "Chinquapin",
            "Chippewa",
            "Chituris",
            "Choctaw",
            "Chopin",
            "Chow Chow",
            "Chris",
            "Chris Albert",
            "Christiansen",
            "Christine",
            "Christmas Tree",
            "Christoffersen",
            "Christopher",
            "Christy",
            "Chronicle",
            "Chrysler",
            "Chukar",
            "Church",
            "Churchill",
            "Churchill Downs",
            "Cicada",
            "Ciccarelli",
            "Cielito",
            "Cimarron",
            "Cimarron Hills",
            "Cimarron Trail",
            "Cindy",
            "Cinnabar",
            "Cinnamon",
            "Cinnamon Teal",
            "Cipponeri",
            "Circa",
            "Circle",
            "Circus",
            "Citation",
            "Citrine",
            "Citrus",
            "Claimstake",
            "Claire",
            "Clairmont",
            "Clara",
            "Claradell",
            "Claratina",
            "Claremont",
            "Clarence",
            "Clarendon",
            "Claret",
            "Claribel",
            "Clark",
            "Clarks Mill",
            "Clarksburg",
            "Classic",
            "Claud",
            "Claus",
            "Clausen",
            "Clay",
            "Clay Ridge",
            "Claymont",
            "Clayton",
            "Clear Creek",
            "Clearview",
            "Clearwater",
            "Clementa",
            "Clementina",
            "Clemson",
            "Cleta",
            "Cleveland",
            "Clevenger",
            "Cliff",
            "Cliff Swallow",
            "Clifford",
            "Cliffside",
            "Cliffwood",
            "Clifton",
            "Cling",
            "Clinton",
            "Clipper",
            "Clock Tower",
            "Clogston",
            "Clotilde",
            "Cloutier",
            "Clove",
            "Clover",
            "Cloverdale",
            "Cloverland",
            "Clovewood",
            "Clubhouse",
            "Clydesdale",
            "Coad",
            "Coastal",
            "Cobbler",
            "Cobblestone",
            "Cobblestone Manor",
            "Coconut Palm",
            "Court",
            "Courtney",
            "Courtyard",
            "Covena",
            "Coventry",
            "Coventry Garden",
            "Covered Bridge",
            "Covert",
            "Covey",
            "Coville",
            "Covington",
            "Cowan",
            "Cox",
            "Coyado",
            "Coye Oak",
            "Coyote",
            "Coyote Run",
            "Cozy",
            "Crabapple",
            "Crabtree",
            "Crackerbox",
            "Craig",
            "Crandall",
            "Crane",
            "Cranford",
            "Crater",
            "Crawford",
            "Creamery",
            "Credence",
            "Creedmoor",
            "Creek",
            "Creek Bed",
            "Creek Bend",
            "Creek Park",
            "Creek View",
            "Creekpaum",
            "Creekside",
            "Creekwood",
            "Creole",
            "Crescendo",
            "Crescent",
            "Crescent Moon",
            "Cressy",
            "Cresta",
            "Crested Bobwhite",
            "Crestmont",
            "Crestmoor",
            "Crestview",
            "Crestwood",
            "Crete",
            "Crevison",
            "Crevison Peak",
            "Cribari",
            "Crimson",
            "Criolla",
            "Crippen",
            "Crismon",
            "Crocker",
            "Crockett",
            "Crocus",
            "Crommelin",
            "Cromwell",
            "Crossbill",
            "Crossing",
            "Crossroads",
            "Crosswood",
            "Crow",
            "Crow Creek",
            "Crow Hill",
            "Edward",
            "Edwin",
            "Effingham",
            "Ehlers",
            "Ehrlich",
            "Eicher",
            "Eider",
            "Eisenhower",
            "El Cajon",
            "El Camino",
            "El Capitan",
            "Flint",
            "Flintridge",
            "Flora",
            "Flora Vista",
            "Floral",
            "Florence",
            "Flores",
            "Florette",
            "Florida",
            "Heston",
            "Hi Tech Parkway",
            "Hialeah",
            "Hickey",
            "La Linda",
            "La Loma",
            "Locksley",
            "Lockwood",
            "Locust",
            "Lodge Creek",
            "Lodgepole",
            "Lodi",
            "Logan",
            "Loire",
            "Lois",
            "Lola",
            "Loletta",
            "Loma",
            "Loma Vista",
            "Lombardo",
            "Lombardy",
            "Lon Dale",
            "London",
            "Londonderry",
            "Lone Oak",
            "Lone Palm",
            "Lone Tree",
            "Lonepine",
            "Lonestar",
            "Long",
            "Longbridge",
            "Longfellow",
            "Longhorn",
            "Longmeadow",
            "Loni",
            "Lookout",
            "Loquat",
            "Lorainne",
            "Lord",
            "Lorelei",
            "Lorene",
            "Lorenzo",
            "Malta",
            "Malvern",
            "Mamilane",
            "Masterpiece",
            "Matalea",
            "Mather",
            "Mathia",
            "Matisse",
            "Matterhorn",
            "Matthew",
            "Maud",
            "Maud Kump Terrace",
            "Maui Terrace",
            "Mauna Kea",
            "Mauna Loa",
            "Maura",
            "Maverick",
            "Mavis",
            "Mawana",
            "Max",
            "Maximillian",
            "Maxine",
            "Maxwell",
            "May",
            "Mayberry",
            "Mayette",
            "Mayfair",
            "Mayfaire",
            "Mayfield",
            "Mayflower",
            "Maynell",
            "Mayo",
            "Maywood",
            "Mazanita",
            "Maze",
            "Mc Adoo",
            "Mc Allister",
            "Mc Caffrey",
            "Mc Clintock",
            "Mc Clure",
            "Mc Cormick",
            "Mc Coy",
            "Mc Cracken",
            "Mc Devitt",
            "Mc Donald",
            "Mc Ewen",
            "Mc Gee",
            "Mc Gerry",
            "Mc Ginn",
            "Mc Ginnis",
            "Mc Guire",
            "Mc Henry",
            "Mc Henry Village",
            "Mc Kinley",
            "Mc Kittrick",
            "Mc Kosato",
            "Mc Leod",
            "Mc Murphy",
            "Mc Nary",
            "Mc Naughton",
            "Mc Neff",
            "Mc Neil",
            "Mc Reynolds",
            "Mc Ritchie",
            "Mc Williams",
            "Mcarthur",
            "Mccauly",
            "Mccord",
            "Mcdonald",
            "Mcintosh",
            "Mckenna",
            "Mcknight",
            "Meadow",
            "Meadow Brook",
            "Meadow Creek",
            "Meadow Glen",
            "Meadow Grove",
            "Meadow Oak",
            "Meadow Rue",
            "Meadowgate",
            "Meadowlark",
            "Meadowmont",
            "Meadowood",
            "Meadowview",
            "Meandering",
            "Mechalys",
            "Medallion",
            "Medeiros",
            "Medford",
            "Medicine Bow",
            "Medinah",
            "Mediterranean",
            "Medlin",
            "Megan",
            "Meghan",
            "Meier",
            "Meikle",
            "Meily",
            "Melanie",
            "Melba",
            "Melbourne",
            "Melgren",
            "Melinda",
            "Melissa",
            "Mello",
            "Mellor",
            "Melody",
            "Melones",
            "Melrose",
            "Melva",
            "Melville",
            "Memorial",
            "Memory",
            "Memphis",
            "Mendocino",
            "Mendocino Creek",
            "Menlo",
            "Mensinger",
            "Merced",
            "Mercer",
            "Merchant",
            "Mercy",
            "Merganser",
            "Meridian",
            "Merle",
            "Merlin",
            "Merlot",
            "Merriam",
            "Merrifield",
            "Merrimac",
            "Merriment",
            "Merritt",
            "Merton",
            "Mertz",
            "Mesa",
            "Mesa Creek",
            "Mesa Verde",
            "Mesquite",
            "Mesrob",
            "Messara",
            "Messenger",
            "Messer",
            "Meta",
            "Metcalf",
            "Mettler",
            "Meyer",
            "Mezzo",
            "Miadora",
            "Mica",
            "Michael",
            "Monte Carlo",
            "Monte Cristo",
            "Monte Verde",
            "Monte Vista",
            "Murphy",
            "Murray",
            "Murrietta",
            "Muscat",
            "Nora",
            "Nordell",
            "Orchid",
            "Oregon",
            "Orestimba",
            "Peach",
            "Peach Blossom",
            "Peachcrest",
            "Pinecone",
            "Pinecrest",
            "Pinehurst",
            "Plumeria",
            "Plumwood",
            "Quiet Wood",
            "Quigley",
            "Quilling",
            "Quince",
            "Quincy",
            "Quinturn",
            "Quisenberry",
            "Rabbit Hill",
            "Race",
            "Raceway",
            "Rachelle",
            "Radcliffe",
            "Reunion",
            "Revere",
            "Rexford",
            "Rochester",
            "Rock Creek",
            "Rock Pine",
            "Rock River",
            "Rockefeller",
            "Roselena",
            "Roselene",
            "Roselle",
            "Rosemary",
            "Rosemead",
            "Rosemont",
            "Rosemore",
            "Rosenthal",
            "Rosetti",
            "Rosewood",
            "Rosina",
            "Roslyn",
            "Ross",
            "Rossini",
            "Rossmoor",
            "Rosso",
            "Roswell",
            "Roth",
            "Rothbury",
            "Rothchild",
            "Rotterdam",
            "Rouse",
            "Rowland",
            "Roxanne",
            "Roxbury",
            "Roy Dan",
            "Royal Ann",
            "Royal Ascot",
            "Royal Links",
            "Royal Windsor",
            "Royal Wood",
            "Royalton",
            "Rozanna",
            "Rubens",
            "Ruberto",
            "Ruble",
            "Ruby",
            "Ruddy",
            "Rudge",
            "Rue De Yoe",
            "Ruffed Grouse",
            "Ruffian",
            "Ruffino",
            "Rugby",
            "Ruisdael",
            "San Gabriel",
            "San Ignacio",
            "San Joaquin",
            "San Juan",
            "San Lucas",
            "San Luis",
            "San Marco",
            "San Marino",
            "San Martin",
            "San Mateo",
            "San Michele",
            "San Miguel",
            "San Moritz",
            "San Paulo",
            "San Pedro",
            "San Rafael",
            "San Ramos",
            "San Remo",
            "San Tropez",
            "San Vincente",
            "San Vito",
            "Sanchez",
            "Sanctuary",
            "Sand Bar",
            "Sand Hill",
            "Sand Stone",
            "Sandalwood",
            "Sandburg",
            "Sandcreek",
            "Sanderling",
            "Sanders",
            "Sandgate",
            "Sandling",
            "Sandpiper",
            "Sandpoint",
            "Sands",
            "Sandstone",
            "Sandstsone",
            "Sandy",
            "Sandy Creek",
            "Sandy Ridge",
            "Sandy View",
            "Sanko",
            "Sanna",
            "Sansome",
            "Santa Ana",
            "Santa Barbara",
            "Santa Cruz",
            "Santa Fe",
            "Santa Lucia",
            "Santa Maria",
            "Santa Paula",
            "Santa Rita",
            "Santa Rosa",
            "Santa Teresa",
            "Santa Ynez",
            "Santiago",
            "Santina",
            "Santos",
            "Sapphire",
            "Sarah",
            "Sarah Jane",
            "Sarah Therese",
            "Saratoga",
            "Saratoga Hills",
            "Sarazen",
            "Sargon",
            "Sarolou",
            "Sarum",
            "Sash",
            "Satariano",
            "Stakes",
            "Stallion",
            "Standford",
            "Standiford",
            "Standing Oak",
            "Standish",
            "Stanford",
            "Stanislaus",
            "Stanislaus River",
            "Stanley",
            "Stanley Allen",
            "Stanton",
            "Stanton Harcourt",
            "Star",
            "Star Oak",
            "Starboard",
            "Starflower",
            "Stark",
            "Starke",
            "Starling",
            "Starlite",
            "Starr",
            "State",
            "State Route 4",
            "Stearns",
            "Steel Creek",
            "Steele",
            "Steeplechase",
            "Stein",
            "Steinbeck",
            "Steitz",
            "Stella",
            "Stembridge",
            "Sun River",
            "Sun Stone",
            "Sun Valley",
            "Sun West",
            "Sunbird",
            "Sunburst",
            "Sunbury",
            "Suncrest",
            "Sundance",
            "Sundance Lake",
            "Sunday",
            "Sundown",
            "Sunfield",
            "Sunflower",
            "Sungate",
            "Sunkist",
            "Sunland",
            "Sunmist",
            "Sunny",
            "Sunny Creek",
            "Sunny Oak",
            "Sunny Park",
            "Sunny Vista",
            "Sunnybrook",
            "Sunnyhill",
            "Sunnyside",
            "Sunnyview",
            "Sunnyway",
            "Sunrise",
            "Sunset",
            "Sunset Meadows",
            "Sunset Terrace",
            "Sunshiine",
            "Waters Edge",
            "Waterthrush",
            "Waterway",
            "Watson",
            "Watts",
            "Waverly",
            "Wawona",
            "Waxwing",
            "Wayne",
            "Waynesboro",
            "Wayside",
            "Weathervane",
            "Webb",
            "Weber",
            "Webster",
            "Wedgewood",
            "Welara",
            "Welch",
            "Weldon",
            "Wellerman",
            "Wellesley",
            "Wellington",
            "Wells",
            "Wellsford",
            "Welty",
            "Wendy",
            "Wentworth",
            "Wesley",
            "Wessex",
            "Wesson Ranch",
            "West",
            "West Main",
            "Wexford",
            "Weyer",
            "Weymouth",
            "Wharf",
            "Wheatley",
            "Wheeler Peak",
            "Whippoorwill",
            "Whirlaway",
            "Whisper",
            "Whispering Oak",
            "Whispering Pines",
            "Whistler",
            "Whitcomb",
            "White",
            "White Birch",
            "White Dove",
            "White Fall",
            "White Oak",
            "Wild Palms",
            "Wild Poppy",
            "Wild Rose",
            "Wilder",
            "Wildermuth",
            "Wilderness Oaks",
            "Wildflower",
            "Wildtree",
            "Wildwood",
            "Wiley",
            "Wilkesboro",
            "Wilkins",
            "Will Scarlet",
            "Willeen",
            "Willert",
            "Willetts",
            "Williams",
            "Williamsburg",
            "Willms",
            "Willow",
            "Willow Bend",
            "Willowood",
            "Willowsong",
            "Wilma",
            "Wilmer",
            "Wilmington",
            "Woodwind",
            "Woodworth",
            "Woolston",
            "Woonsocket",
            "Workman",
            "Worthington",
            "Wrangler",
            "Wren",
            "Wright",
            "Wyatt",
            "Wycliffe",
            "Wylie",
            "Wylma",
            "Wylmawood",
            "Wyndfair",
            "Wyndmoor",
            "Xavier",
            "Yale",
            "Yalonda",
            "Yamamoto",
            "Yancey",
            "Yankee",
            "Yarmouth",
            "Yarrow",
            "Yearling",
            "Yellow Brick",
            "Yellow Oak",
            "Yellow Pine",
            "Yellowhammer",
            "Yellowstone",
            "Yellowstone Park",
            "Yerington",
            "Yolo",
            "Yolo Creek",
            "Yonan",
            "York",
            "Yorkshire",
            "Yorkton",
            "Yorktown",
            "Yosemite",
            "Yosemite Meadows",
            "Yosemite Park",
            "Zenith",
            "Zephyr",
            "Zerillo",
            "Zina",
            "Zinfandel",
            "Zinnia",
            "Zuccaro",
            "Zurich"
        };
    }
}
