using System.Collections.Generic;
using TestFramework;

namespace TestFramework.Data.Lists
{
    public class CityDataList : IDataList<string>
    {
        public virtual List<string> List => new List<string>()
        {
            "Aberdeen",
            "Abilene",
            "Acworth",
            "Ada",
            "Adrian",
            "Akron",
            "Albany",
            "Albion",
            "Albuquerque",
            "Alexandria",
            "Aliso Viejo",
            "Allen",
            "Allendale",
            "Allentown",
            "Aloha",
            "Alpharetta",
            "Altamonte Springs",
            "Altoona",
            "Amarillo",
            "Ames",
            "Amherst",
            "Anaheim",
            "Anchorage",
            "Anderson",
            "Andover",
            "Ann Arbor",
            "Annapolis",
            "Antioch",
            "Apopka",
            "Apple Valley",
            "Appleton",
            "Arcadia",
            "Arlington",
            "Arvada",
            "Asheboro",
            "Asheville",
            "Ashland",
            "Ashtabula",
            "Astoria",
            "Athens",
            "Atlanta",
            "Auburn",
            "Augusta",
            "Aurora",
            "Austin",
            "Avon",
            "Avondale",
            "Bakersfield",
            "Baltimore",
            "Bartlett",
            "Batavia",
            "Baton Rouge",
            "Battle Creek",
            "Bay City",
            "Baytown",
            "Bear",
            "Beaufort",
            "Beaumont",
            "Beavercreek",
            "Beaverton",
            "Bedford",
            "Belleville",
            "Bellevue",
            "Bellingham",
            "Belmont",
            "Beloit",
            "Belton",
            "Bend",
            "Benton",
            "Berea",
            "Berkeley",
            "Berwyn",
            "Bethesda",
            "Bethlehem",
            "Bettendorf",
            "Big Rapids",
            "Billings",
            "Birmingham",
            "Blaine",
            "Bloomfield",
            "Bloomington",
            "Boca Raton",
            "Boise",
            "Bolingbrook",
            "Boone",
            "Boonville",
            "Bossier City",
            "Boston",
            "Bothell",
            "Bowie",
            "Bowling Green",
            "Boynton Beach",
            "Bradenton",
            "Brandon",
            "Brazil",
            "Brea",
            "Bremerton",
            "Brentwood",
            "Bridgeport",
            "Brighton",
            "Bristol",
            "Broken Arrow",
            "Bronx",
            "Brookfield",
            "Brooklyn",
            "Brooksville",
            "Brookville",
            "Brownsburg",
            "Brownsville",
            "Brunswick",
            "Bryan",
            "Buena Park",
            "Buffalo",
            "Burbank",
            "Burleson",
            "Burlington",
            "Burton",
            "Butler",
            "Byron Center",
            "Cadillac",
            "Caledonia",
            "Cambridge",
            "Camden",
            "Canton",
            "Cape Coral",
            "Carlisle",
            "Carlsbad",
            "Carmel",
            "Carrollton",
            "Carson",
            "Carthage",
            "Cary",
            "Cedar Park",
            "Cedar Rapids",
            "Cedar Springs",
            "Centennial",
            "Centerville",
            "Centralia",
            "Champaign",
            "Chandler",
            "Chapel Hill",
            "Charleston",
            "Charlotte",
            "Charlottesville",
            "Chatsworth",
            "Chattanooga",
            "Cherry Hill",
            "Chesapeake",
            "Chester",
            "Chesterfield",
            "Chicago",
            "Chillicothe",
            "Chula Vista",
            "Cincinnati",
            "Claremont",
            "Clarksville",
            "Clayton",
            "Clearwater",
            "Cleveland",
            "Clifton",
            "Clinton",
            "Clovis",
            "Coatesville",
            "Cocoa",
            "Coldwater",
            "College Station",
            "Collinsville",
            "Colorado Springs",
            "Columbia",
            "Columbia City",
            "Columbus",
            "Comstock Park",
            "Concord",
            "Conroe",
            "Conway",
            "Conyers",
            "Cookeville",
            "Coon Rapids",
            "Coral Springs",
            "Cordova",
            "Corona",
            "Corpus Christi",
            "Corvallis",
            "Costa Mesa",
            "Cottage Grove",
            "Council Bluffs",
            "Covington",
            "Crawfordsville",
            "Crossville",
            "Cumberland",
            "Cumming",
            "Cuyahoga Falls",
            "Cypress",
            "Dallas",
            "Dalton",
            "Danville",
            "Davenport",
            "Davie",
            "Dayton",
            "Decatur",
            "Defiance",
            "Deland",
            "Delaware",
            "Delray Beach",
            "Deltona",
            "Denton",
            "Denver",
            "Derby",
            "Deridder",
            "Des Moines",
            "Detroit",
            "Dickson",
            "Douglasville",
            "Dover",
            "Downingtown",
            "Dublin",
            "Dubuque",
            "Duluth",
            "Durham",
            "Eagan",
            "Easley",
            "East Lansing",
            "East Peoria",
            "Easton",
            "Eden",
            "Edmond",
            "El Cajon",
            "El Paso",
            "Elgin",
            "Elizabeth",
            "Elizabethtown",
            "Elk Grove",
            "Elkhart",
            "Elkhorn",
            "Elkton",
            "Ellensburg",
            "Elyria",
            "Englewood",
            "Ephrata",
            "Erie",
            "Escondido",
            "Eugene",
            "Euless",
            "Eureka",
            "Evansville",
            "Everett",
            "Fairborn",
            "Fairfax",
            "Fairfield",
            "Fairmont",
            "Fairview",
            "Falls Church",
            "Farmington",
            "Fayetteville",
            "Federal Way",
            "Fenton",
            "Findlay",
            "Fishers",
            "Flagstaff",
            "Flint",
            "Florence",
            "Florissant",
            "Flushing",
            "Fond Du Lac",
            "Fontana",
            "Forest Grove",
            "Fort Collins",
            "Fort Lauderdale",
            "Fort Myers",
            "Fort Smith",
            "Fort Wayne",
            "Fort Worth",
            "Fountain Valley",
            "Frankfort",
            "Franklin",
            "Frederick",
            "Fredericksburg",
            "Freeport",
            "Fremont",
            "Fresno",
            "Frisco",
            "Ft. Myers",
            "Fullerton",
            "Gainesville",
            "Gaithersburg",
            "Galesburg",
            "Gallatin",
            "Garden City",
            "Garden Grove",
            "Gardena",
            "Garland",
            "Gastonia",
            "Geneva",
            "Georgetown",
            "Germantown",
            "Gig Harbor",
            "Gilbert",
            "Gladstone",
            "Glasgow",
            "Glendale",
            "Goodlettsville",
            "Goshen",
            "Grafton",
            "Graham",
            "Granbury",
            "Grand Haven",
            "Grand Junction",
            "Grand Prairie",
            "Grand Rapids",
            "Grandville",
            "Grants Pass",
            "Great Falls",
            "Green Bay",
            "Greenfield",
            "Greensboro",
            "Greensburg",
            "Greenville",
            "Greenwood",
            "Greer",
            "Gresham",
            "Grove City",
            "Gulfport",
            "Hagerstown",
            "Hamburg",
            "Hamilton",
            "Hammond",
            "Hampton",
            "Hanover",
            "Harrisburg",
            "Harrison",
            "Hartford",
            "Hastings",
            "Hawthorne",
            "Hayward",
            "Helena",
            "Henderson",
            "Hendersonville",
            "Hermitage",
            "Hesperia",
            "Hickory",
            "High Point",
            "Highland",
            "Hilliard",
            "Hillsboro",
            "Hixson",
            "Holland",
            "Hollywood",
            "Homestead",
            "Honolulu",
            "Hot Springs",
            "Houston",
            "Hudson",
            "Hudsonville",
            "Humble",
            "Huntington",
            "Huntington Beach",
            "Huntsville",
            "Huron",
            "Hurst",
            "Hutchinson",
            "Independence",
            "Indianapolis",
            "Indpls",
            "Ionia",
            "Iowa City",
            "Ironton",
            "Irvine",
            "Irving",
            "Jackson",
            "Jacksonville",
            "Jamestown",
            "Janesville",
            "Jasper",
            "Jefferson",
            "Jeffersonville",
            "Jenison",
            "Jersey City",
            "Johnson City",
            "Johnstown",
            "Joliet",
            "Jonesboro",
            "Kalamazoo",
            "Kansas City",
            "Katy",
            "Keizer",
            "Keller",
            "Kennesaw",
            "Kennewick",
            "Kenosha",
            "Kent",
            "Kentwood",
            "Kernersville",
            "Kettering",
            "Killeen",
            "Kingman",
            "Kingsport",
            "Kingston",
            "Kirkland",
            "Kissimmee",
            "Klamath Falls",
            "Knoxville",
            "Kokomo",
            "La Habra",
            "Lacey",
            "Lafayette",
            "Lagrange",
            "Laguna Hills",
            "Laguna Niguel",
            "Lake Charles",
            "Lake City",
            "Lake Forest",
            "Lake Oswego",
            "Lake Worth",
            "Lakeland",
            "Lakewood",
            "Lancaster",
            "Lansing",
            "Laredo",
            "Largo",
            "Las Cruces",
            "Las Vegas",
            "Laurel",
            "Lawrence",
            "Lawrenceburg",
            "Lawrenceville",
            "Lawton",
            "Lebanon",
            "Leesburg",
            "Lehigh Acres",
            "Lewisburg",
            "Lewiston",
            "Lewisville",
            "Lexington",
            "Liberty",
            "Lima",
            "Lincoln",
            "Lincolnton",
            "Linden",
            "Linton",
            "Little Rock",
            "Littleton",
            "Livingston",
            "Lockport",
            "Lodi",
            "London",
            "Long Beach",
            "Longview",
            "Longwood",
            "Lorain",
            "Los Angeles",
            "Louisville",
            "Loveland",
            "Lowell",
            "Lubbock",
            "Lufkin",
            "Lumberton",
            "Lynchburg",
            "Lynnwood",
            "Macon",
            "Madison",
            "Magnolia",
            "Malvern",
            "Manassas",
            "Manchester",
            "Mansfield",
            "Maple Grove",
            "Maple Valley",
            "Maplewood",
            "Marietta",
            "Marion",
            "Marshall",
            "Martinez",
            "Martinsburg",
            "Martinsville",
            "Marysville",
            "Maryville",
            "Mason",
            "Massillon",
            "Matthews",
            "Mcdonough",
            "Mckinney",
            "Mcminnville",
            "Mechanicsburg",
            "Mechanicsville",
            "Medford",
            "Medina",
            "Melbourne",
            "Memphis",
            "Merced",
            "Mesa",
            "Mesquite",
            "Metairie",
            "Miami",
            "Miamisburg",
            "Middleburg",
            "Middletown",
            "Midland",
            "Midlothian",
            "Milan",
            "Milford",
            "Milton",
            "Milwaukee",
            "Milwaukie",
            "Minneapolis",
            "Mishawaka",
            "Mission Viejo",
            "Missoula",
            "Mobile",
            "Modesto",
            "Moline",
            "Monroe",
            "Montgomery",
            "Monticello",
            "Montrose",
            "Moore",
            "Mooresville",
            "Moreno Valley",
            "Morgantown",
            "Morristown",
            "Morton",
            "Moses Lake",
            "Mount Airy",
            "Mount Pleasant",
            "Mount Vernon",
            "Mountain View",
            "Mt. Pleasant",
            "Mt. Vernon",
            "Muncie",
            "Murfreesboro",
            "Muscatine",
            "Muskegon",
            "Myrtle Beach",
            "Nampa",
            "Naperville",
            "Naples",
            "Nashua",
            "Nashville",
            "Nederland",
            "New Albany",
            "New Braunfels",
            "New Castle",
            "New Haven",
            "New London",
            "New Orleans",
            "New Port Richey",
            "New York",
            "Newark",
            "Newburgh",
            "Newnan",
            "Newport",
            "Newport Beach",
            "Newport News",
            "Newton",
            "Nicholasville",
            "Niles",
            "Noblesville",
            "Norcross",
            "Norfolk",
            "Normal",
            "Norman",
            "North Fort Myers",
            "North Hollywood",
            "North Las Vegas",
            "Northridge",
            "Norwalk",
            "Oak Harbor",
            "Oak Park",
            "Oakdale",
            "Oakland",
            "Ocala",
            "Oceanside",
            "Odessa",
            "Oklahoma City",
            "Olathe",
            "Old Hickory",
            "Olympia",
            "Omaha",
            "Ontario",
            "Orange",
            "Orange Park",
            "Oregon",
            "Oregon City",
            "Orlando",
            "Orrville",
            "Oshkosh",
            "Ottawa",
            "Overland Park",
            "Oviedo",
            "Owensboro",
            "Oxford",
            "Oxnard",
            "Paducah",
            "Palm Bay",
            "Palm Coast",
            "Palmdale",
            "Palmyra",
            "Panama City",
            "Paris",
            "Parker",
            "Parma",
            "Pasadena",
            "Pearland",
            "Pekin",
            "Pendleton",
            "Pensacola",
            "Peoria",
            "Perry",
            "Perrysburg",
            "Peru",
            "Petaluma",
            "Petersburg",
            "Phila",
            "Philadelphia",
            "Phoenix",
            "Phoenixville",
            "Pineville",
            "Piqua",
            "Pittsburgh",
            "Pittsfield",
            "Placentia",
            "Plainfield",
            "Plano",
            "Plant City",
            "Plantation",
            "Plymouth",
            "Pomona",
            "Port Angeles",
            "Port Charlotte",
            "Port Huron",
            "Port Orange",
            "Port Orchard",
            "Portage",
            "Portland",
            "Portsmouth",
            "Pottstown",
            "Powell",
            "Prescott",
            "Princeton",
            "Providence",
            "Pueblo",
            "Pulaski",
            "Punta Gorda",
            "Puyallup",
            "Queen Creek",
            "Quincy",
            "Racine",
            "Raleigh",
            "Rancho Santa Margarita",
            "Ravenna",
            "Reading",
            "Redmond",
            "Redondo Beach",
            "Reidsville",
            "Reno",
            "Renton",
            "Richardson",
            "Richland",
            "Richmond",
            "Ringgold",
            "Rio Rancho",
            "Riverside",
            "Riverview",
            "Roanoke",
            "Rochester",
            "Rock Hill",
            "Rock Island",
            "Rockford",
            "Rockville",
            "Rome",
            "Roseville",
            "Rossville",
            "Roswell",
            "Round Rock",
            "Russellville",
            "Sacramento",
            "Saginaw",
            "Saint Charles",
            "Saint Louis",
            "Saint Paul",
            "Saint Petersburg",
            "Salem",
            "Salina",
            "Salinas",
            "Salisbury",
            "Salt Lake City",
            "San Angelo",
            "San Antonio",
            "San Bernardino",
            "San Clemente",
            "San Diego",
            "San Francisco",
            "San Jose",
            "San Marcos",
            "San Pedro",
            "Sandusky",
            "Sanford",
            "Santa Ana",
            "Santa Barbara",
            "Santa Clara",
            "Santa Cruz",
            "Santa Fe",
            "Santa Monica",
            "Santa Rosa",
            "Sarasota",
            "Savannah",
            "Schenectady",
            "Scottsdale",
            "Seattle",
            "Seymour",
            "Shawnee",
            "Sheboygan",
            "Shelby",
            "Shelbyville",
            "Shelton",
            "Sheridan",
            "Sherman",
            "Sherman Oaks",
            "Sherwood",
            "Shreveport",
            "Sidney",
            "Silsbee",
            "Silver Spring",
            "Simi Valley",
            "Simpsonville",
            "Sioux City",
            "Sioux Falls",
            "Slidell",
            "Smithville",
            "Smyrna",
            "Snellville",
            "Somerset",
            "Somerville",
            "South Bend",
            "Spanaway",
            "Sparta",
            "Spartanburg",
            "Spencer",
            "Spokane",
            "Spring",
            "Spring Hill",
            "Spring Lake",
            "Springfield",
            "St Louis",
            "St Paul",
            "St. Charles",
            "St. Louis",
            "St. Paul",
            "St. Petersburg",
            "Stafford",
            "Stanton",
            "Staten Island",
            "Statesville",
            "Staunton",
            "Sterling",
            "Stillwater",
            "Stockbridge",
            "Stockton",
            "Stone Mountain",
            "Stratford",
            "Sugar Land",
            "Sullivan",
            "Summerville",
            "Sun Prairie",
            "Sunnyvale",
            "Surprise",
            "Syracuse",
            "Tacoma",
            "Tallahassee",
            "Tampa",
            "Taylorsville",
            "Temecula",
            "Tempe",
            "Temple",
            "Terre Haute",
            "Texarkana",
            "Thomasville",
            "Tiffin",
            "Tigard",
            "Tinley Park",
            "Toledo",
            "Topeka",
            "Torrance",
            "Traverse City",
            "Trenton",
            "Trinity",
            "Troy",
            "Tucson",
            "Tulsa",
            "Tustin",
            "Tyler",
            "Union",
            "Union City",
            "Uniontown",
            "Upland",
            "Urbana",
            "Utica",
            "Valdosta",
            "Valparaiso",
            "Valrico",
            "Van Nuys",
            "Vancouver",
            "Venice",
            "Ventura",
            "Versailles",
            "Victoria",
            "Vidor",
            "Vienna",
            "Vincennes",
            "Virginia Beach",
            "Visalia",
            "Vista",
            "Waco",
            "Wadsworth",
            "Warner Robins",
            "Warren",
            "Warsaw",
            "Washington",
            "Waterford",
            "Waterloo",
            "Watertown",
            "Waukesha",
            "Waverly",
            "Wayne",
            "Waynesboro",
            "Waynesville",
            "Weatherford",
            "Webster",
            "Wellington",
            "West Allis",
            "West Bend",
            "West Chester",
            "West Covina",
            "West Des Moines",
            "West Lafayette",
            "West Monroe",
            "West Palm Beach",
            "Westerville",
            "Westfield",
            "Westminster",
            "Weston",
            "Wheeling",
            "Whitehall",
            "Whittier",
            "Wichita",
            "Williamsburg",
            "Williamstown",
            "Wilmington",
            "Winchester",
            "Windsor",
            "Winston Salem",
            "Winston-Salem",
            "Winter Haven",
            "Woodbridge",
            "Woodbury",
            "Woodland",
            "Woodland Hills",
            "Woodstock",
            "Wooster",
            "Worcester",
            "Wyoming",
            "Xenia",
            "Yakima",
            "Yorba Linda",
            "York",
            "Youngstown",
            "Yuma",
            "Zanesville",
            "Zeeland",
        };
    }
}
